name: Weasel License Validation
on:
  push:
  create:
  pull_request:
jobs:
  weasel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run weasel
        uses: docker://licenseweasel/weasel:v0.4
        with:
          args: "-d app"
